# Generated by Django 4.2 on 2026-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField()),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_profile_id', models.IntegerField()),
                ('Customer_profile_name', models.TextField()),
                ('Customer_profile_image', models.TextField()),
                ('Customer_profile_phone', models.TextField()),
                ('Customer_email', models.TextField()),
            ],
        ),
    ]
